"""DOCX report generator — slim 2-page format."""
from __future__ import annotations
from pathlib import Path

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

from casmd.report.data import ReportData


def generate_docx(data: ReportData, output_path: Path) -> Path:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = Document()

    # ---- Title ----
    title = doc.add_heading(f"CasMD report — {data.job_name}", level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(f"Production length: {data.production_ns:.0f} ns")
    run.font.size = Pt(10)

    # ---- Structure prediction (if present) ----
    if data.prediction is not None:
        doc.add_heading("Structure prediction", level=2)
        pred_table = doc.add_table(rows=2, cols=4)
        pred_table.style = "Light Grid Accent 1"
        hdr = pred_table.rows[0].cells
        hdr[0].text = "Backend"
        hdr[1].text = "Model"
        hdr[2].text = "iPTM"
        hdr[3].text = "pTM"
        row = pred_table.rows[1].cells
        row[0].text = data.prediction.backend
        row[1].text = str(data.prediction.model_id)
        row[2].text = f"{data.prediction.iptm:.3f}" if data.prediction.iptm is not None else "--"
        row[3].text = f"{data.prediction.ptm:.3f}" if data.prediction.ptm is not None else "--"

    # ---- Simulation summary ----
    doc.add_heading("Simulation summary", level=2)
    ana = data.analysis
    sim_table = doc.add_table(rows=5, cols=2)
    sim_table.style = "Light Grid Accent 1"
    rows = [
        ("Frames", str(ana.n_frames)),
        ("Equilibration discard", f"{ana.equil_skip} frames (first 20%)"),
        ("Protein Cα RMSD (equilibrated mean)", _fmt(ana.protein_rmsd_equil_mean_A, "Å")),
        ("Protein Cα RMSF (mean)", _fmt(ana.protein_rmsf_mean_A, "Å")),
        ("Protein Rg (equilibrated mean)", _fmt(ana.protein_rg_equil_mean_A, "Å")),
    ]
    for i, (k, v) in enumerate(rows):
        sim_table.rows[i].cells[0].text = k
        sim_table.rows[i].cells[1].text = v

    # ---- Interpretation ----
    doc.add_heading("Interpretation", level=2)
    doc.add_paragraph(data.interpretation)

    # ---- Figures (page break, then 3 plots) ----
    doc.add_page_break()
    doc.add_heading("Dynamics plots", level=2)
    for key, caption in (("rmsd", "Protein Cα RMSD"),
                          ("rmsf", "Per-residue RMSF"),
                          ("rg", "Radius of gyration")):
        if key in data.figures and data.figures[key].exists():
            doc.add_picture(str(data.figures[key]), width=Inches(6.0))
            p = doc.add_paragraph(caption)
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            r = p.runs[0]
            r.italic = True
            r.font.size = Pt(9)

    doc.save(str(output_path))
    return output_path


def _fmt(v: float | None, unit: str) -> str:
    if v is None:
        return "--"
    return f"{v:.2f} {unit}"


def generate_comparison_docx(cd, out_path) -> None:
    """Write a 2-column comparison DOCX report.

    cd: ComparisonData
    out_path: pathlib.Path or str
    """
    from pathlib import Path as _Path

    out_path = _Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    doc = Document()

    # Title
    doc.add_heading(f"Comparison: {cd.label_a} vs {cd.label_b}", level=1)
    p = doc.add_paragraph("Generated by CasMD v0.9.1")
    p.runs[0].italic = True

    # 1. Summary table
    doc.add_heading("Summary", level=2)
    table = doc.add_table(rows=1, cols=6)
    try:
        table.style = "Light Grid Accent 1"
    except Exception:
        table.style = "Table Grid"
    hdr = table.rows[0].cells
    hdr[0].text = "Metric"
    hdr[1].text = cd.label_a
    hdr[2].text = cd.label_b
    hdr[3].text = "Δ"
    hdr[4].text = "p-value"
    hdr[5].text = "Significant?"
    for key, stat in cd.stats.items():
        row = table.add_row().cells
        row[0].text = key.upper()
        row[1].text = f"{stat.mean_a:.2f}"
        row[2].text = f"{stat.mean_b:.2f}"
        row[3].text = f"{stat.delta:+.2f}"
        # NaN check: float('nan') != float('nan')
        row[4].text = "—" if stat.pvalue != stat.pvalue else f"{stat.pvalue:.3g}"
        row[5].text = "✓" if stat.significant else "—"

    # 2. Alignment info
    if cd.residue_map is not None:
        doc.add_heading("Sequence alignment", level=2)
        doc.add_paragraph(
            f"Pairwise identity: {cd.residue_map.identity_pct * 100:.1f}%. "
            f"{len(cd.residue_map.aligned_segments)} aligned segment(s)."
        )

    # 3. Figures (skipped if not provided)
    if cd.figures_a or cd.figures_b:
        doc.add_heading("Dynamics", level=2)
        for key in ("rmsd", "rmsf", "rg"):
            if key in cd.figures_a:
                doc.add_paragraph(f"{key.upper()} — {cd.label_a}")
                doc.add_picture(str(cd.figures_a[key]), width=Inches(5.5))
            if key in cd.figures_b:
                doc.add_paragraph(f"{key.upper()} — {cd.label_b}")
                doc.add_picture(str(cd.figures_b[key]), width=Inches(5.5))

    # 4. Interpretation
    if cd.interpretation:
        doc.add_heading("Interpretation", level=2)
        doc.add_paragraph(cd.interpretation)

    # 5. Citations
    doc.add_heading("Cite this work", level=2)
    doc.add_paragraph(
        "Zhao, Z., & Hsing, I.-M. (2026). CasMD: an online toolkit for "
        "protein–nucleic acid molecular dynamics simulation. Hsing Lab, HKUST. "
        "Unpublished. Version 0.9.1."
    )

    doc.save(str(out_path))
